feat : #9 add bookmark test and service
hhPlusDeliverySystem/delivery_system pull request #10
Opened 2023-07-03 18:56 UTC by hoduulmu

this close #9 

## 해결하려는 문제가 무엇인가요?
- 즐겨찾기 등록 및 취소 테스트 코드 및 서비스 코드 추가입니다

## 어떻게 해결했나요?
- `jest.spyon()`으로 `StoreRepository`와 `BookmarkRepository` 의 메소드를 처리했습니다

## 어떤 부분에 집중하여 리뷰해야 할까요?
- `jest.spyon(storeRepository.existStoreById())`의 경우 실패 테스트를 짜면서 추가되었고 이미 위에 짜놓았던 2개의 테스트에도 추가하게 되었습니다
- 개인적인 생각으로 이렇게 내부 구현이 계속 테스트에  영향을 주는게 좀 이상하다 생각이 들어서 `beforeEach` 에서 `Store` 엔티티를 저장하거나 하는 방향으로 나중에 바꿔보고 싶은데 어떻게 생각하시는지 궁금합니다!

2023-07-04 01:26 UTC, pyuseon commented
재훈님 고생 많으셨습니다. 👍 

저도 내부 구조가  test에 이렇게 영향을 주는게 맞는지 service가 바뀌면 테스트가 다 바뀌어야 하는게 맞는지 고민이 되네용 
이부분은 같이 이야기 해봐도 될 것 같습니다. 😄 

Exception도 잘 handling 해주셨네요 고생하셨습니다! 
이 부분은 저희 통일하기로 했던 형식으로 추후 변경이 필요하겠네요!
Controller 작성까지 화이팅 입니다!

2023-07-04 17:31 UTC, yunju2 requested changes
재훈님 고생하셨습니다!👏
저도 각 테스트가 서로 영향을 주는 것이 좋지 않다고 생각하여 beforeEach 에 Store 엔티티를 저장하는 것이 좋은 방법인 거 같습니다.ㅎㅎ
코드를 보는데 몇가지 코멘트 달고 싶은 내용이 있어 하기에 정리해놨습니다.!
- storeRepository에서 existStoreById가 없습니다. 빠진 거 같습니당🤔
-  bookmark.entity.ts를 보면 객체 생성하는 create 메서드를 만드신 거 같은데 따로 만드실 필요없이  typeorm repository api 사용하시면 되겠습니다. 참고하시라고 링크 남기겠습니다! https://orkhan.gitbook.io/typeorm/docs/repository-api

2023-07-05 06:52 UTC, hoduulmu commented
윤주님 요청하신점 수정해서 다시 리뷰 요청했습니다!

2023-07-05 11:34 UTC, yunju2 approved these changes

2023-07-05 12:42 UTC, merged